apiVersion: apps/v1
kind: Deployment
metadata:
    name: mproduct-depl
spec:
  replicas: 1
  selector:
      matchLabels:
        app: mproduct
  template:
    metadata:
        labels:
            app: mproduct
    spec:
      containers:
          - name: mproduct 
            image: tohshine/mproduct
            
            env:
              - name: MONGO_URL
                value: mongodb://mproduct-mongo-srv:27017/mproduct
              - name: NAT_CLUSTER_ID
                value: market
              - name: NAT_URL
                value: 'http://nats-srv:4222'
              - name: NAT_CLIENT_ID
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.name
              - name: JWT_KEY
                valueFrom:
                  secretKeyRef:
                    name: jwt-secret
                    key: JWT_KEY
              - name: CLOUD_KEY
                valueFrom:
                  secretKeyRef:
                    name: cloudinary-secret
                    key: CLOUD_KEY
---
apiVersion: v1
kind: Service
metadata:
   name: mproduct-srv
spec:
   selector:
    app: mproduct
   ports:
    - name: mproduct
      protocol: TCP
      port: 3000
      targetPort: 3000   

