apiVersion: apps/v1
kind: Deployment
metadata:
    name: morder-mongo-depl
spec:
  replicas: 1
  selector:
      matchLabels:
        app: morder-mongo
  template:
    metadata:
        labels:
            app: morder-mongo
    spec:
      containers:
          - name: morder-mongo
            image: mongo
---
apiVersion: v1
kind: Service
metadata:
   name: morder-mongo-srv
spec:
   selector:
    app: morder-mongo
   ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017   

