apiVersion: apps/v1
kind: Deployment
metadata:
    name: mproduct-mongo-depl
spec:
  replicas: 1
  selector:
      matchLabels:
        app: mproduct-mongo
  template:
    metadata:
        labels:
            app: mproduct-mongo
    spec:
      containers:
          - name: mproduct-mongo
            image: mongo
---
apiVersion: v1
kind: Service
metadata:
   name: mproduct-mongo-srv
spec:
   selector:
    app: mproduct-mongo
   ports:
    - name: db
      protocol: TCP
      port: 27017
      targetPort: 27017   

