name: depl-manifest

on:
  push:
    branches: 
      - master
    paths:
      - 'infra/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 #it copy all current repository  folder
      - uses: digitalocean/action-doctl@v2 #it preinstall digital ocean CLI inside github containers 
        with:
          token:  ${{secrets.DIGITAL_OCCEAN_ACCESS_TOKEN}}
      - run: doctl kubernetes cluster kubeconfig save sellit
      - run: |
         kubectl apply -f infra/k8s
         kubectl apply -f infra/dbs
         kubectl apply -f infra/k8s-prod  
